# Email templates translations
# English

## Email footer
email-footer-generated-by = Automatically generated by
email-footer-do-not-reply = This is an automated email. Please do not reply.
email-footer-link-sdi = SDI Portal
email-footer-link-help = Help

## Common email terms
email-common-invoice = Invoice
email-common-client = Client
email-common-date = Date
email-common-amount = Amount
email-common-status = Status
email-common-details = Details
email-common-view-details = View Details
email-common-total = Total
email-common-subtotal = Subtotal
email-common-vat = VAT
email-common-errors = Errors
email-common-error = Error
email-common-success = Success
email-common-warning = Warning

## SDI - Invio Fattura
email-sdi-invio-subject = Invoice { $numero }/{ $anno } Sent to SDI
email-sdi-invio-title = Electronic Invoice Transmission
email-sdi-invio-intro = The invoice has been sent to the Exchange System (SDI) for delivery to the recipient.
email-sdi-invio-invoice-details = Invoice Details
email-sdi-invio-sender-info = Sender Information
email-sdi-invio-attached-file = Attached file
email-sdi-invio-next-steps = Next Steps
email-sdi-invio-next-steps-text = You will receive a notification when the invoice is delivered to the recipient. The process may take a few hours.

## SDI - Notifica Attestazione (RC)
email-sdi-attestazione-subject = 📨 Invoice { $numero }/{ $anno } - Transmission Confirmed
email-sdi-attestazione-title = Transmission Attestation
email-sdi-attestazione-intro = The Exchange System (SDI) confirms receipt of the invoice.
email-sdi-attestazione-message = The invoice has been accepted by the system and will be forwarded to the recipient.
email-sdi-attestazione-sdi-id = SDI Identifier

## SDI - Notifica Consegna (NS)
email-sdi-consegna-subject = ✅ Invoice { $numero }/{ $anno } Delivered
email-sdi-consegna-title = Invoice Delivered Successfully
email-sdi-consegna-intro = The invoice has been successfully delivered to the recipient.
email-sdi-consegna-message = The Exchange System has confirmed delivery of the invoice to the customer's system.
email-sdi-consegna-delivered-at = Delivered on
email-sdi-consegna-next-steps = Now wait for the customer's outcome (acceptance or rejection).

## SDI - Notifica Scarto (NS rifiuto)
email-sdi-scarto-subject = ❌ Invoice { $numero }/{ $anno } Rejected by SDI
email-sdi-scarto-title = Invoice Rejected
email-sdi-scarto-intro = The invoice has been rejected by the Exchange System due to validation errors.
email-sdi-scarto-error-list = Error List
email-sdi-scarto-action-required = Action Required
email-sdi-scarto-action-text = Correct the indicated errors and resend the invoice to the Exchange System.
email-sdi-scarto-error-count = { $count ->
    [one] { $count } error detected
   *[other] { $count } errors detected
}

## SDI - Mancata Consegna (MC)
email-sdi-mancata-consegna-subject = ⚠️ Invoice { $numero }/{ $anno } - Failed Delivery
email-sdi-mancata-consegna-title = Failed Delivery
email-sdi-mancata-consegna-intro = The Exchange System was unable to deliver the invoice to the recipient.
email-sdi-mancata-consegna-reason = Reason
email-sdi-mancata-consegna-action-required = Action Required
email-sdi-mancata-consegna-action-text = Verify recipient details (PEC or Recipient Code) and resend the invoice with correct information.

## SDI - Esito Committente Accettata (EC01)
email-sdi-esito-accettata-subject = ✅ Invoice { $numero }/{ $anno } Accepted by Customer
email-sdi-esito-accettata-title = Invoice Accepted
email-sdi-esito-accettata-intro = The customer has accepted the invoice.
email-sdi-esito-accettata-message = The invoice has been validated and accepted by the recipient. The invoicing process is successfully completed.
email-sdi-esito-accettata-outcome = Customer Outcome
email-sdi-esito-accettata-accepted = Accepted (EC01)

## SDI - Esito Committente Rifiutata (EC02)
email-sdi-esito-rifiutata-subject = ⚠️ Invoice { $numero }/{ $anno } Rejected by Customer
email-sdi-esito-rifiutata-title = Invoice Rejected
email-sdi-esito-rifiutata-intro = The customer has rejected the invoice.
email-sdi-esito-rifiutata-message = The recipient has rejected the invoice. Contact the customer for clarification.
email-sdi-esito-rifiutata-outcome = Customer Outcome
email-sdi-esito-rifiutata-rejected = Rejected (EC02)
email-sdi-esito-rifiutata-reason = Reason
email-sdi-esito-rifiutata-action-required = Action Required
email-sdi-esito-rifiutata-action-text = Contact the customer to understand the reasons for rejection. A credit note may be required.

## Batch Operations
email-batch-summary-subject = Batch Operation Summary - { $operation }
email-batch-summary-title = Batch Operation Summary
email-batch-summary-operation = Operation
email-batch-summary-started-at = Started at
email-batch-summary-completed-at = Completed at
email-batch-summary-duration = Duration
email-batch-summary-metrics = Metrics
email-batch-summary-total-items = Total Items
email-batch-summary-processed = Processed
email-batch-summary-succeeded = Succeeded
email-batch-summary-failed = Failed
email-batch-summary-success-rate = Success Rate
email-batch-summary-errors = Errors Detected
email-batch-summary-no-errors = No errors
email-batch-summary-results = Results
email-batch-summary-download-csv = Download CSV Report

## Test Email
email-test-subject = PEC Configuration Test - OpenFatture
email-test-title = PEC Configuration Test
email-test-intro = This is a test message to verify the PEC configuration.
email-test-success = If you receive this message, the configuration is correct!
email-test-server-info = Server Information
email-test-smtp-server = SMTP Server
email-test-smtp-port = SMTP Port
email-test-pec-address = PEC Address
email-test-time = Test performed on
