"""Add nota di credito linkage fields to Fattura

Revision ID: 8cf82bd24752
Revises: 21807fbe7cd6
Create Date: 2026-09-11 17:33:29.903102

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8cf82bd24752'
down_revision: str | Sequence[str] | None = '21807fbe7cd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=27), nullable=True),
    sa.Column('bic_swift', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts'))
    )
    op.create_index(op.f('ix_bank_accounts_iban'), 'bank_accounts', ['iban'], unique=True)
    op.create_table('clienti',
    sa.Column('denominazione', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('partita_iva', sa.String(length=11), nullable=True),
    sa.Column('regime_fiscale', sa.String(length=4), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=True),
    sa.Column('numero_civico', sa.String(length=10), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('comune', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('nazione', sa.String(length=2), nullable=False),
    sa.Column('codice_destinatario', sa.String(length=7), nullable=True),
    sa.Column('pec', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clienti'))
    )
    op.create_index(op.f('ix_clienti_codice_fiscale'), 'clienti', ['codice_fiscale'], unique=False)
    op.create_index(op.f('ix_clienti_denominazione'), 'clienti', ['denominazione'], unique=False)
    op.create_index(op.f('ix_clienti_partita_iva'), 'clienti', ['partita_iva'], unique=False)
    op.create_table('event_log',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    op.create_index('ix_event_log_entity', 'event_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_event_log_entity_id'), 'event_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_log_entity_type'), 'event_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_log_event_id'), 'event_log', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_occurred_at'), 'event_log', ['occurred_at'], unique=False)
    op.create_index('ix_event_log_type_occurred', 'event_log', ['event_type', 'occurred_at'], unique=False)
    op.create_table('model_prediction_feedback',
    sa.Column('prediction_type', sa.Enum('INVOICE_DELAY', 'TAX_SUGGESTION', 'DESCRIPTION_GENERATION', 'CLIENT_RECOMMENDATION', name='predictiontype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('prediction_data', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('user_accepted', sa.Boolean(), nullable=False),
    sa.Column('user_correction', sa.Text(), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_prediction_feedback'))
    )
    op.create_index(op.f('ix_model_prediction_feedback_created_at'), 'model_prediction_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_prediction_feedback_entity_id'), 'model_prediction_feedback', ['entity_id'], unique=False)
    op.create_index(op.f('ix_model_prediction_feedback_prediction_type'), 'model_prediction_feedback', ['prediction_type'], unique=False)
    op.create_index(op.f('ix_model_prediction_feedback_processed'), 'model_prediction_feedback', ['processed'], unique=False)
    op.create_table('prodotti',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=500), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aliquota_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unita_misura', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('is_servizio', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prodotti'))
    )
    op.create_index(op.f('ix_prodotti_codice'), 'prodotti', ['codice'], unique=True)
    op.create_table('user_feedback',
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('feedback_type', sa.Enum('RATING', 'CORRECTION', 'COMMENT', 'THUMBS_UP', 'THUMBS_DOWN', name='feedbacktype'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('feature_name', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_feedback'))
    )
    op.create_index(op.f('ix_user_feedback_agent_type'), 'user_feedback', ['agent_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_created_at'), 'user_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_feedback_feedback_type'), 'user_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_session_id'), 'user_feedback', ['session_id'], unique=False)
    op.create_table('preventivi',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('data_emissione', sa.Date(), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('imponibile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stato', sa.Enum('BOZZA', 'INVIATO', 'ACCETTATO', 'RIFIUTATO', 'SCADUTO', 'CONVERTITO', name='statopreventivo'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('condizioni', sa.Text(), nullable=True),
    sa.Column('validita_giorni', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_preventivi_cliente_id_clienti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preventivi'))
    )
    op.create_index(op.f('ix_preventivi_anno'), 'preventivi', ['anno'], unique=False)
    op.create_index(op.f('ix_preventivi_numero'), 'preventivi', ['numero'], unique=False)
    op.create_table('fatture',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('data_emissione', sa.Date(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('TD01', 'TD02', 'TD03', 'TD04', 'TD05', 'TD06', 'TD16', 'TD17', 'TD18', 'TD19', 'TD20', 'TD21', 'TD22', 'TD23', 'TD24', 'TD25', 'TD26', 'TD27', name='tipodocumento'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('preventivo_id', sa.Integer(), nullable=True),
    sa.Column('imponibile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ritenuta_acconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aliquota_ritenuta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('importo_bollo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fattura_collegata_id', sa.Integer(), nullable=True),
    sa.Column('fattura_collegata_numero', sa.String(length=20), nullable=True),
    sa.Column('fattura_collegata_data', sa.Date(), nullable=True),
    sa.Column('stato', sa.Enum('BOZZA', 'DA_INVIARE', 'INVIATA', 'CONSEGNATA', 'ACCETTATA', 'RIFIUTATA', 'SCARTATA', 'ERRORE', name='statofattura'), nullable=False),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('xml_firmato_path', sa.String(length=500), nullable=True),
    sa.Column('numero_sdi', sa.String(length=50), nullable=True),
    sa.Column('data_invio_sdi', sa.DateTime(), nullable=True),
    sa.Column('data_consegna_sdi', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('fk_fatture_cliente_id_clienti')),
    sa.ForeignKeyConstraint(['fattura_collegata_id'], ['fatture.id'], name=op.f('fk_fatture_fattura_collegata_id_fatture')),
    sa.ForeignKeyConstraint(['preventivo_id'], ['preventivi.id'], name=op.f('fk_fatture_preventivo_id_preventivi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fatture'))
    )
    op.create_index(op.f('ix_fatture_anno'), 'fatture', ['anno'], unique=False)
    op.create_index(op.f('ix_fatture_fattura_collegata_id'), 'fatture', ['fattura_collegata_id'], unique=False)
    op.create_index(op.f('ix_fatture_numero'), 'fatture', ['numero'], unique=False)
    op.create_table('righe_preventivo',
    sa.Column('preventivo_id', sa.Integer(), nullable=False),
    sa.Column('numero_riga', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unita_misura', sa.String(length=10), nullable=False),
    sa.Column('aliquota_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('imponibile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preventivo_id'], ['preventivi.id'], name=op.f('fk_righe_preventivo_preventivo_id_preventivi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_righe_preventivo'))
    )
    op.create_table('dati_cassa_previdenziale',
    sa.Column('fattura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cassa', sa.String(length=4), nullable=False),
    sa.Column('al_cassa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('importo_contributo_cassa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imponibile_cassa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aliquota_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ritenuta', sa.String(length=2), nullable=True),
    sa.Column('natura', sa.String(length=10), nullable=True),
    sa.Column('riferimento_amministrazione', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], name=op.f('fk_dati_cassa_previdenziale_fattura_id_fatture')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dati_cassa_previdenziale'))
    )
    op.create_table('log_sdi',
    sa.Column('fattura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_notifica', sa.String(length=10), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('data_ricezione', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], name=op.f('fk_log_sdi_fattura_id_fatture')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_sdi'))
    )
    op.create_table('pagamenti',
    sa.Column('fattura_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importo_pagato', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('stato', sa.Enum('DA_PAGARE', 'PAGATO_PARZIALE', 'PAGATO', 'SCADUTO', name='statopagamento'), nullable=False),
    sa.Column('modalita', sa.String(length=50), nullable=False),
    sa.Column('iban', sa.String(length=27), nullable=True),
    sa.Column('bic_swift', sa.String(length=11), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], name=op.f('fk_pagamenti_fattura_id_fatture')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamenti'))
    )
    op.create_table('righe_fattura',
    sa.Column('fattura_id', sa.Integer(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=True),
    sa.Column('numero_riga', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unita_misura', sa.String(length=10), nullable=False),
    sa.Column('aliquota_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('natura', sa.String(length=10), nullable=True),
    sa.Column('imponibile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], name=op.f('fk_righe_fattura_fattura_id_fatture')),
    sa.ForeignKeyConstraint(['prodotto_id'], ['prodotti.id'], name=op.f('fk_righe_fattura_prodotto_id_prodotti'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_righe_fattura'))
    )
    op.create_index(op.f('ix_righe_fattura_prodotto_id'), 'righe_fattura', ['prodotto_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('counterparty_iban', sa.String(length=27), nullable=True),
    sa.Column('status', sa.Enum('UNMATCHED', 'MATCHED', 'IGNORED', name='transactionstatus'), nullable=False),
    sa.Column('matched_payment_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'FUZZY', 'IBAN', 'DATE_WINDOW', 'COMPOSITE', 'MANUAL', name='matchtype'), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_source', sa.Enum('CSV', 'OFX', 'QIF', 'MANUAL', name='importsource'), nullable=False),
    sa.Column('import_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], name=op.f('fk_bank_transactions_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['pagamenti.id'], name=op.f('fk_bank_transactions_matched_payment_id_pagamenti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transactions'))
    )
    op.create_index(op.f('ix_bank_transactions_amount'), 'bank_transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transactions_counterparty_iban'), 'bank_transactions', ['counterparty_iban'], unique=False)
    op.create_index(op.f('ix_bank_transactions_date'), 'bank_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    op.create_index('ix_bank_transactions_status_date', 'bank_transactions', ['status', 'date'], unique=False)
    op.create_table('payment_reminders',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('days_before_due', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('strategy', sa.Enum('DEFAULT', 'AGGRESSIVE', 'GENTLE', 'MINIMAL', name='reminderstrategy'), nullable=False),
    sa.Column('email_template', sa.String(length=100), nullable=False),
    sa.Column('email_subject', sa.String(length=200), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['pagamenti.id'], name=op.f('fk_payment_reminders_payment_id_pagamenti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_reminders'))
    )
    op.create_index(op.f('ix_payment_reminders_payment_id'), 'payment_reminders', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_reminders_reminder_date'), 'payment_reminders', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_payment_reminders_status'), 'payment_reminders', ['status'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'FUZZY', 'IBAN', 'DATE_WINDOW', 'COMPOSITE', 'MANUAL', name='matchtype'), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['pagamenti.id'], name=op.f('fk_payment_allocations_payment_id_pagamenti')),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], name=op.f('fk_payment_allocations_transaction_id_bank_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_transaction_id'), 'payment_allocations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_transaction_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_payment_reminders_status'), table_name='payment_reminders')
    op.drop_index(op.f('ix_payment_reminders_reminder_date'), table_name='payment_reminders')
    op.drop_index(op.f('ix_payment_reminders_payment_id'), table_name='payment_reminders')
    op.drop_table('payment_reminders')
    op.drop_index('ix_bank_transactions_status_date', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_counterparty_iban'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_amount'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_righe_fattura_prodotto_id'), table_name='righe_fattura')
    op.drop_table('righe_fattura')
    op.drop_table('pagamenti')
    op.drop_table('log_sdi')
    op.drop_table('dati_cassa_previdenziale')
    op.drop_table('righe_preventivo')
    op.drop_index(op.f('ix_fatture_numero'), table_name='fatture')
    op.drop_index(op.f('ix_fatture_fattura_collegata_id'), table_name='fatture')
    op.drop_index(op.f('ix_fatture_anno'), table_name='fatture')
    op.drop_table('fatture')
    op.drop_index(op.f('ix_preventivi_numero'), table_name='preventivi')
    op.drop_index(op.f('ix_preventivi_anno'), table_name='preventivi')
    op.drop_table('preventivi')
    op.drop_index(op.f('ix_user_feedback_session_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_type'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_created_at'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_agent_type'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_prodotti_codice'), table_name='prodotti')
    op.drop_table('prodotti')
    op.drop_index(op.f('ix_model_prediction_feedback_processed'), table_name='model_prediction_feedback')
    op.drop_index(op.f('ix_model_prediction_feedback_prediction_type'), table_name='model_prediction_feedback')
    op.drop_index(op.f('ix_model_prediction_feedback_entity_id'), table_name='model_prediction_feedback')
    op.drop_index(op.f('ix_model_prediction_feedback_created_at'), table_name='model_prediction_feedback')
    op.drop_table('model_prediction_feedback')
    op.drop_index('ix_event_log_type_occurred', table_name='event_log')
    op.drop_index(op.f('ix_event_log_occurred_at'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_entity_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_entity_id'), table_name='event_log')
    op.drop_index('ix_event_log_entity', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_clienti_partita_iva'), table_name='clienti')
    op.drop_index(op.f('ix_clienti_denominazione'), table_name='clienti')
    op.drop_index(op.f('ix_clienti_codice_fiscale'), table_name='clienti')
    op.drop_table('clienti')
    op.drop_index(op.f('ix_bank_accounts_iban'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
